services:
  {{PROJECT_NAME}}:
    build:
      context: .
      dockerfile: Dockerfile
    image: {{PROJECT_NAME}}:local
    container_name: {{PROJECT_NAME}}
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    restart: unless-stopped
